hydra:
  job:
    chdir: True
  run:
    dir: outputs/${hydra.job.name}/test=${test}/${dataset_name}/${model_name}/${seed}
dataset_name: azure_vm_traces_2017
model_name: ...
test: False
data_path: "Salesforce/cloudops_tsf"
storage: sqlite:///${hydra:runtime.cwd}/benchmark_exp.db
n_trials: 15
max_trials: 15
batch_size: 128
num_workers: 12
epochs: 100
num_batches_per_epoch: 100
seed: 0
